Suggested changes to linux_config to make more user customizable.
rjmccabe3701/linux_config pull request #2
Opened 2017-06-29 18:31 UTC by savagesmc

I have done a few cleanups of things i saw in the vimrc file and the other config files, as well as moving user specific configuration (user name in .gitconfig for example) out to user specific files that can be provided in the root directory through another mechanism.

2017-06-29 18:46 UTC, rjmccabe3701 commented on gitconfig
> +    smtpserver = smtpimr.rockwellcollins.com
I dont agree with this.

2017-06-30 12:38 UTC, rjmccabe3701 requested changes

2017-06-30 12:38 UTC, rjmccabe3701 commented on vimrc
> +Plugin 'vim-scripts/a.vim'
What is a.vim?

2017-06-30 12:38 UTC, rjmccabe3701 commented on gitconfig
> +    smtpserver = smtpimr.rockwellcollins.com
I dont agree with this.

2017-06-30 12:38 UTC, rjmccabe3701 commented on vimrc
> +set wildignore+=.git\*,.hg\*,.svn\*,*.d,*.dbo,*.o,*.ti,*.a,*.so
what does this ignore?

2017-06-30 14:29 UTC, savagesmc commented on vimrc
> +Plugin 'vim-scripts/a.vim'
Alternate macros to switch between header and source files easily.

2017-06-30 14:30 UTC, savagesmc commented on vimrc
> +set wildignore+=.git\*,.hg\*,.svn\*,*.d,*.dbo,*.o,*.ti,*.a,*.so
Skips over repo overhead folders and build intermediate files for ctrl-p.

2017-06-30 15:59 UTC, merged